### ISSUE TITLE
[feature request] any plan for FreeBSD support?

### ISSUE THREAD

**Issue by gesund** [iawia002/annie#25]
Thank you for this gorgeous work, I love it.

It seems FreeBSD is not supported yet, and the darwin binary shows 'Exec format error' on FreeBSD--it works on macOS only, just as expected.

I tried annie linux-amd64 binary(v0.4.1) on FreeBSD 11.1-RELEASE-p8 with CentOS 7 compatibility layer, only to get the 'Segmentation fault' error.

I know this project is on its early stage and FreeBSD is much less popular than Linux, but if you'd like to take native FreeBSD support into consideration, I'll greatly appreciate that.

FreeBSD用的人少，但它确实是一款优秀的操作系统，发这个issue也算是给它打个广告吧 :)

**Comment by iawia002** [comment]
hi @gesund, Actually, the early version of Annie(https://github.com/iawia002/annie/releases/tag/0.2.2, thanks to Go, cross-platform is simple) supports FreeBSD, and later I thought it was niche, so I didn't compile the version that supports FreeBSD.

Since there is a need now, the next version will support FreeBSD.

**Comment by iawia002** [comment]
@gesund https://github.com/iawia002/annie/releases/tag/0.5.0, have a try

**Comment by gesund** [comment]
It works like magic, thank you iawia002 !
