### ISSUE TITLE
youtube-dl

### ISSUE THREAD

**Issue by vi** [iawia002/annie#57]
There is already [youtube-dl](https://github.com/rg3/youtube-dl) project, which despite of the name supports multiple sites, not just YouTube.

Annie's README should provide comparison with youtube-dl or at least mention it as alternative.

**Comment by iawia002** [comment]
hi @vi, thanks for your suggestion.

As I mentioned in [About the project](https://github.com/iawia002/annie#about-this-project), Annie is just a sudden idea. I want to build a simple but strong downloader. Unlike the other existing ones, I wanted to use static language from the beginning, because it will make the code easier to maintain, and the code can also be understood faster even without documentation, so I chose Go. I didn't expect that Annie got so many attention.

 I'll mention youtube-dl in README first and think about our difference.

**Comment by vi** [comment]
Will it also cover [plowshare](https://github.com/mcrapet/plowshare) functionality then?

**Comment by lamg** [comment]
I was using youtube-dl until the first time I tried annie.

**Comment by iawia002** [comment]
@vi you mean mention plowshare in README too? I don't think Annie and plowshare are the same thing

**Comment by vi** [comment]
I expected "I want to build a simple but strong downloader." to mean "download anything from anywhere: videos, files, books, photos, pastebins, code from Github etc."
